window.LINGUABRIDGE_EXTRA_DECKS = [
  {
    id: "ko-everyday-core",
    language: "ko",
    type: "韩语日常核心",
    title: "韩语日常核心词 1",
    description: "生活、校园、出行和基础会话中最常见的韩语词。",
    words: [
      { term: "가다", pronunciation: "ga-da", meaning: "去", example: "수업이 끝나고 친구와 도서관에 가요.", synonyms: ["이동하다"], antonyms: ["오다"], partOfSpeech: "动词" },
      { term: "오다", pronunciation: "o-da", meaning: "来", example: "비가 와서 집에 조금 늦게 왔어요.", synonyms: ["도착하다"], antonyms: ["가다"], partOfSpeech: "动词" },
      { term: "보다", pronunciation: "bo-da", meaning: "看、见", example: "주말에 보고 싶었던 영화를 봤어요.", synonyms: ["구경하다", "살펴보다"], antonyms: [], partOfSpeech: "动词" },
      { term: "듣다", pronunciation: "deut-da", meaning: "听", example: "버스에서 한국어 팟캐스트를 들었어요.", synonyms: ["청취하다"], antonyms: ["말하다"], partOfSpeech: "动词" },
      { term: "말하다", pronunciation: "mal-ha-da", meaning: "说", example: "처음 만난 사람에게 천천히 말해 달라고 했어요.", synonyms: ["이야기하다"], antonyms: ["듣다"], partOfSpeech: "动词" },
      { term: "읽다", pronunciation: "ik-da", meaning: "读", example: "모르는 단어가 있어도 문장 전체를 먼저 읽어 봤어요.", synonyms: ["독서하다"], antonyms: ["쓰다"], partOfSpeech: "动词" },
      { term: "쓰다", pronunciation: "sseu-da", meaning: "写、使用", example: "새로 배운 표현을 일기장에 써 봤어요.", synonyms: ["작성하다", "사용하다"], antonyms: ["읽다"], partOfSpeech: "动词" },
      { term: "먹다", pronunciation: "meok-da", meaning: "吃", example: "시험이 끝난 뒤에 친구들과 김치찌개를 먹었어요.", synonyms: ["식사하다"], antonyms: [], partOfSpeech: "动词" },
      { term: "마시다", pronunciation: "ma-si-da", meaning: "喝", example: "아침마다 따뜻한 차를 마시면서 단어를 외워요.", synonyms: ["음용하다"], antonyms: [], partOfSpeech: "动词" },
      { term: "자다", pronunciation: "ja-da", meaning: "睡觉", example: "내일 발표가 있어서 오늘은 일찍 자려고 해요.", synonyms: ["잠을 자다"], antonyms: ["깨다"], partOfSpeech: "动词" },
      { term: "일어나다", pronunciation: "i-reo-na-da", meaning: "起床、发生", example: "아침에 일어나자마자 알림을 확인했어요.", synonyms: ["기상하다", "발생하다"], antonyms: ["눕다"], partOfSpeech: "动词" },
      { term: "쉬다", pronunciation: "swi-da", meaning: "休息", example: "오래 공부한 뒤에는 잠깐 쉬는 것도 필요해요.", synonyms: ["휴식하다"], antonyms: ["일하다"], partOfSpeech: "动词" },
      { term: "일하다", pronunciation: "il-ha-da", meaning: "工作", example: "방학 동안 카페에서 일하면서 한국어를 연습했어요.", synonyms: ["근무하다"], antonyms: ["쉬다"], partOfSpeech: "动词" },
      { term: "만나다", pronunciation: "man-na-da", meaning: "见面", example: "수업 후에 선생님을 만나 질문을 드렸어요.", synonyms: ["마주치다"], antonyms: ["헤어지다"], partOfSpeech: "动词" },
      { term: "헤어지다", pronunciation: "he-eo-ji-da", meaning: "分开、告别", example: "친구와 헤어진 뒤에도 메시지로 계속 이야기했어요.", synonyms: ["이별하다"], antonyms: ["만나다"], partOfSpeech: "动词" },
      { term: "사다", pronunciation: "sa-da", meaning: "买", example: "서점에서 한국어 문법책을 한 권 샀어요.", synonyms: ["구입하다"], antonyms: ["팔다"], partOfSpeech: "动词" },
      { term: "팔다", pronunciation: "pal-da", meaning: "卖", example: "동아리 바자회에서 직접 만든 간식을 팔았어요.", synonyms: ["판매하다"], antonyms: ["사다"], partOfSpeech: "动词" },
      { term: "빌리다", pronunciation: "bil-li-da", meaning: "借", example: "도서관에서 TOPIK 문제집을 빌렸어요.", synonyms: ["대여하다"], antonyms: ["돌려주다"], partOfSpeech: "动词" },
      { term: "돌려주다", pronunciation: "dol-lyeo-ju-da", meaning: "归还", example: "친구에게 빌린 노트를 수업 전에 돌려줬어요.", synonyms: ["반납하다"], antonyms: ["빌리다"], partOfSpeech: "动词" },
      { term: "기다리다", pronunciation: "gi-da-ri-da", meaning: "等待", example: "버스를 기다리는 동안 단어 카드를 봤어요.", synonyms: ["대기하다"], antonyms: [], partOfSpeech: "动词" },
      { term: "늦다", pronunciation: "neut-da", meaning: "迟、晚", example: "길이 막혀서 약속 시간에 조금 늦었어요.", synonyms: ["지각하다"], antonyms: ["이르다"], partOfSpeech: "形容词" },
      { term: "빠르다", pronunciation: "ppa-reu-da", meaning: "快", example: "그 친구는 한국어를 배우는 속도가 정말 빨라요.", synonyms: ["신속하다"], antonyms: ["느리다"], partOfSpeech: "形容词" },
      { term: "느리다", pronunciation: "neu-ri-da", meaning: "慢", example: "처음에는 말하기가 느렸지만 점점 자연스러워졌어요.", synonyms: ["더디다"], antonyms: ["빠르다"], partOfSpeech: "形容词" },
      { term: "쉽다", pronunciation: "swip-da", meaning: "容易", example: "예문이 자연스러우면 단어를 기억하기 쉬워요.", synonyms: ["간단하다"], antonyms: ["어렵다"], partOfSpeech: "形容词" },
      { term: "어렵다", pronunciation: "eo-ryeop-da", meaning: "难", example: "발음은 어렵지만 계속 들으면 익숙해져요.", synonyms: ["힘들다"], antonyms: ["쉽다"], partOfSpeech: "形容词" },
      { term: "재미있다", pronunciation: "jae-mi-it-da", meaning: "有趣", example: "친구와 역할극을 하니까 회화 연습이 재미있었어요.", synonyms: ["흥미롭다"], antonyms: ["재미없다"], partOfSpeech: "形容词" },
      { term: "조용하다", pronunciation: "jo-yong-ha-da", meaning: "安静", example: "조용한 카페에서 듣기 문제를 풀었어요.", synonyms: ["고요하다"], antonyms: ["시끄럽다"], partOfSpeech: "形容词" },
      { term: "시끄럽다", pronunciation: "si-kkeu-reop-da", meaning: "吵闹", example: "밖이 시끄러워서 이어폰을 끼고 공부했어요.", synonyms: ["소란스럽다"], antonyms: ["조용하다"], partOfSpeech: "形容词" },
      { term: "깨끗하다", pronunciation: "kkae-kkeut-ha-da", meaning: "干净", example: "깨끗한 책상에 앉으면 공부가 더 잘돼요.", synonyms: ["청결하다"], antonyms: ["더럽다"], partOfSpeech: "形容词" },
      { term: "바쁘다", pronunciation: "ba-ppeu-da", meaning: "忙", example: "요즘 바빠도 하루에 열 단어는 꼭 복습해요.", synonyms: ["분주하다"], antonyms: ["한가하다"], partOfSpeech: "形容词" },
      { term: "한가하다", pronunciation: "han-ga-ha-da", meaning: "空闲", example: "주말에 한가하면 한국 드라마를 보면서 표현을 정리해요.", synonyms: ["여유롭다"], antonyms: ["바쁘다"], partOfSpeech: "形容词" },
      { term: "기분", pronunciation: "gi-bun", meaning: "心情", example: "새 문장을 자연스럽게 말해서 기분이 좋았어요.", synonyms: ["마음", "느낌"], antonyms: [], partOfSpeech: "名词" },
      { term: "약속", pronunciation: "yak-sok", meaning: "约定", example: "친구와 도서관에서 만나기로 약속했어요.", synonyms: ["예약", "다짐"], antonyms: [], partOfSpeech: "名词" },
      { term: "길", pronunciation: "gil", meaning: "路", example: "처음 가는 길이라서 지도를 보면서 걸었어요.", synonyms: ["도로", "방향"], antonyms: [], partOfSpeech: "名词" },
      { term: "버스", pronunciation: "beo-seu", meaning: "公交车", example: "버스를 타고 학교까지 삼십 분쯤 걸려요.", synonyms: ["시내버스"], antonyms: [], partOfSpeech: "名词" },
      { term: "지하철", pronunciation: "ji-ha-cheol", meaning: "地铁", example: "출근 시간에는 지하철 사람이 정말 많아요.", synonyms: ["전철"], antonyms: [], partOfSpeech: "名词" },
      { term: "카페", pronunciation: "ka-pe", meaning: "咖啡馆", example: "카페 창가 자리에 앉아 작문을 고쳤어요.", synonyms: ["커피숍"], antonyms: [], partOfSpeech: "名词" },
      { term: "병원", pronunciation: "byeong-won", meaning: "医院", example: "감기가 심해서 오후에 병원에 다녀왔어요.", synonyms: ["의원"], antonyms: [], partOfSpeech: "名词" },
      { term: "은행", pronunciation: "eun-haeng", meaning: "银行", example: "은행에 가서 계좌를 만들었어요.", synonyms: ["금융기관"], antonyms: [], partOfSpeech: "名词" },
      { term: "우체국", pronunciation: "u-che-guk", meaning: "邮局", example: "우체국에서 가족에게 보낼 선물을 부쳤어요.", synonyms: ["우편국"], antonyms: [], partOfSpeech: "名词" }
    ]
  },
  {
    id: "ko-topik-writing-connectors",
    language: "ko",
    type: "TOPIK 写作连接词",
    title: "TOPIK II 写作连接表达",
    description: "适合中高级写作、阅读和口语表达的自然连接词。",
    words: [
      { term: "그러나", pronunciation: "geu-reo-na", meaning: "但是、然而", example: "시간은 부족했다. 그러나 끝까지 포기하지 않았다.", synonyms: ["하지만"], antonyms: ["따라서"], partOfSpeech: "副词" },
      { term: "하지만", pronunciation: "ha-ji-man", meaning: "但是", example: "문법은 어렵지만 예문을 많이 보면 익숙해진다.", synonyms: ["그러나"], antonyms: [], partOfSpeech: "连接副词" },
      { term: "따라서", pronunciation: "tta-ra-seo", meaning: "因此", example: "꾸준한 복습이 중요하다. 따라서 매일 짧게라도 공부해야 한다.", synonyms: ["그러므로", "결국"], antonyms: [], partOfSpeech: "副词" },
      { term: "그러므로", pronunciation: "geu-reo-meu-ro", meaning: "所以、因此", example: "환경 문제는 모두에게 영향을 준다. 그러므로 함께 해결해야 한다.", synonyms: ["따라서"], antonyms: [], partOfSpeech: "副词" },
      { term: "반면에", pronunciation: "ban-myeon-e", meaning: "相反、另一方面", example: "온라인 수업은 편리하다. 반면에 집중력이 떨어질 수 있다.", synonyms: ["한편"], antonyms: [], partOfSpeech: "副词" },
      { term: "한편", pronunciation: "han-pyeon", meaning: "另一方面", example: "기술은 생활을 편하게 만든다. 한편 개인정보 문제도 생긴다.", synonyms: ["반면에"], antonyms: [], partOfSpeech: "副词" },
      { term: "게다가", pronunciation: "ge-da-ga", meaning: "而且、再加上", example: "이 앱은 사용하기 쉽다. 게다가 예문도 자연스럽다.", synonyms: ["더구나"], antonyms: [], partOfSpeech: "副词" },
      { term: "더구나", pronunciation: "deo-gu-na", meaning: "况且、而且", example: "오늘은 비가 온다. 더구나 바람도 강해서 외출하기 어렵다.", synonyms: ["게다가"], antonyms: [], partOfSpeech: "副词" },
      { term: "특히", pronunciation: "teuk-hi", meaning: "特别是", example: "한국어에서는 조사와 어미가 특히 중요하다.", synonyms: ["무엇보다"], antonyms: [], partOfSpeech: "副词" },
      { term: "무엇보다", pronunciation: "mu-eot-bo-da", meaning: "最重要的是", example: "무엇보다 자연스러운 문장으로 연습하는 것이 필요하다.", synonyms: ["특히"], antonyms: [], partOfSpeech: "副词" },
      { term: "예를 들면", pronunciation: "ye-reul deul-myeon", meaning: "例如", example: "예를 들면, 짧은 대화를 만들어 보면 단어가 더 오래 기억된다.", synonyms: ["예컨대"], antonyms: [], partOfSpeech: "表达" },
      { term: "예컨대", pronunciation: "ye-keon-dae", meaning: "譬如、例如", example: "예컨대 교통, 교육, 환경 문제는 자주 나오는 주제이다.", synonyms: ["예를 들면"], antonyms: [], partOfSpeech: "副词" },
      { term: "결국", pronunciation: "gyeol-guk", meaning: "最终、归根结底", example: "결국 실력은 매일 쌓은 습관에서 나온다.", synonyms: ["마침내", "끝내"], antonyms: ["처음에는"], partOfSpeech: "副词" },
      { term: "마침내", pronunciation: "ma-chim-nae", meaning: "终于", example: "몇 달 동안 연습한 끝에 마침내 자연스럽게 말할 수 있었다.", synonyms: ["드디어"], antonyms: [], partOfSpeech: "副词" },
      { term: "비록", pronunciation: "bi-rok", meaning: "即使、虽然", example: "비록 시간이 오래 걸리더라도 정확하게 이해하는 것이 좋다.", synonyms: ["설령"], antonyms: [], partOfSpeech: "副词" },
      { term: "설령", pronunciation: "seol-lyeong", meaning: "即便、哪怕", example: "설령 실수하더라도 말하기 연습을 멈추면 안 된다.", synonyms: ["비록"], antonyms: [], partOfSpeech: "副词" },
      { term: "오히려", pronunciation: "o-hi-ryeo", meaning: "反而", example: "처음에는 어려웠지만 오히려 그 과정에서 많이 배웠다.", synonyms: ["도리어"], antonyms: [], partOfSpeech: "副词" },
      { term: "도리어", pronunciation: "do-ri-eo", meaning: "反倒", example: "완벽하게 말하려고 하면 도리어 말문이 막힐 때가 있다.", synonyms: ["오히려"], antonyms: [], partOfSpeech: "副词" },
      { term: "또한", pronunciation: "tto-han", meaning: "同时、另外", example: "듣기 연습은 발음에도 도움이 된다. 또한 말하기 자신감도 높여 준다.", synonyms: ["아울러"], antonyms: [], partOfSpeech: "副词" },
      { term: "아울러", pronunciation: "a-ul-leo", meaning: "并且、同时", example: "단어 뜻을 외우고, 아울러 실제 문장 속 쓰임도 확인해야 한다.", synonyms: ["또한"], antonyms: [], partOfSpeech: "副词" },
      { term: "왜냐하면", pronunciation: "wae-nya-ha-myeon", meaning: "因为", example: "예문이 중요하다. 왜냐하면 단어의 분위기까지 배울 수 있기 때문이다.", synonyms: ["그 이유는"], antonyms: [], partOfSpeech: "连接副词" },
      { term: "즉", pronunciation: "jeuk", meaning: "也就是说", example: "복습은 기억을 다시 꺼내는 과정이다. 즉, 단순히 다시 보는 것과 다르다.", synonyms: ["다시 말해"], antonyms: [], partOfSpeech: "副词" },
      { term: "다시 말해", pronunciation: "da-si mal-hae", meaning: "换句话说", example: "다시 말해, 좋은 예문은 단어를 실제 대화로 연결해 준다.", synonyms: ["즉"], antonyms: [], partOfSpeech: "表达" },
      { term: "결론적으로", pronunciation: "gyeol-lon-jeok-eu-ro", meaning: "结论上", example: "결론적으로 언어 학습에는 꾸준함과 자연스러운 입력이 모두 필요하다.", synonyms: ["종합하면"], antonyms: [], partOfSpeech: "副词" },
      { term: "종합하면", pronunciation: "jong-hap-ha-myeon", meaning: "综合来看", example: "종합하면, 단어와 문법은 따로가 아니라 함께 연습해야 한다.", synonyms: ["결론적으로"], antonyms: [], partOfSpeech: "表达" },
      { term: "문제점", pronunciation: "mun-je-jeom", meaning: "问题点", example: "현재 교육 제도의 문제점을 구체적으로 살펴볼 필요가 있다.", synonyms: ["한계", "단점"], antonyms: ["장점"], partOfSpeech: "名词" },
      { term: "장점", pronunciation: "jang-jeom", meaning: "优点", example: "온라인 학습의 가장 큰 장점은 시간과 장소의 제약이 적다는 것이다.", synonyms: ["강점"], antonyms: ["단점"], partOfSpeech: "名词" },
      { term: "단점", pronunciation: "dan-jeom", meaning: "缺点", example: "혼자 공부할 때의 단점은 잘못된 표현을 바로 고치기 어렵다는 점이다.", synonyms: ["약점"], antonyms: ["장점"], partOfSpeech: "名词" },
      { term: "필요성", pronunciation: "pil-yo-seong", meaning: "必要性", example: "외국어 교육의 필요성은 점점 더 커지고 있다.", synonyms: ["중요성"], antonyms: [], partOfSpeech: "名词" },
      { term: "가능성", pronunciation: "ga-neung-seong", meaning: "可能性", example: "꾸준히 연습하면 단기간에도 실력이 향상될 가능성이 있다.", synonyms: ["잠재력"], antonyms: ["불가능성"], partOfSpeech: "名词" }
    ]
  },
  {
    id: "ko-campus-study",
    language: "ko",
    type: "校园学习韩语",
    title: "校园与学习场景词",
    description: "适合留学、课堂、作业、考试和校园生活。",
    words: [
      { term: "강의", pronunciation: "gang-ui", meaning: "课程、讲义", example: "오늘 강의에서는 한국 사회의 변화에 대해 배웠어요.", synonyms: ["수업", "강연"], antonyms: [], partOfSpeech: "名词" },
      { term: "교수님", pronunciation: "gyo-su-nim", meaning: "教授", example: "이메일로 교수님께 면담 시간을 여쭤봤어요.", synonyms: ["선생님"], antonyms: [], partOfSpeech: "名词" },
      { term: "과제", pronunciation: "gwa-je", meaning: "作业、课题", example: "과제를 제출하기 전에 예문을 한 번 더 확인했어요.", synonyms: ["숙제", "프로젝트"], antonyms: [], partOfSpeech: "名词" },
      { term: "제출하다", pronunciation: "je-chul-ha-da", meaning: "提交", example: "보고서를 마감 시간 전에 제출했어요.", synonyms: ["내다"], antonyms: ["돌려받다"], partOfSpeech: "动词" },
      { term: "발표하다", pronunciation: "bal-pyo-ha-da", meaning: "发表、演讲", example: "다음 주에는 조별 과제를 발표해야 해요.", synonyms: ["소개하다", "설명하다"], antonyms: [], partOfSpeech: "动词" },
      { term: "질문하다", pronunciation: "jil-mun-ha-da", meaning: "提问", example: "이해가 안 되는 부분은 바로 질문하는 편이에요.", synonyms: ["묻다"], antonyms: ["대답하다"], partOfSpeech: "动词" },
      { term: "대답하다", pronunciation: "dae-dap-ha-da", meaning: "回答", example: "교수님의 질문에 차분하게 대답했어요.", synonyms: ["답하다"], antonyms: ["질문하다"], partOfSpeech: "动词" },
      { term: "이해하다", pronunciation: "i-hae-ha-da", meaning: "理解", example: "예문을 바꿔 보니 문법을 더 잘 이해하게 됐어요.", synonyms: ["알아듣다"], antonyms: ["오해하다"], partOfSpeech: "动词" },
      { term: "외우다", pronunciation: "oe-u-da", meaning: "背、记忆", example: "단어만 외우지 말고 문장 속에서 익혀야 해요.", synonyms: ["암기하다"], antonyms: ["잊다"], partOfSpeech: "动词" },
      { term: "복습하다", pronunciation: "bok-seup-ha-da", meaning: "复习", example: "잠들기 전에 오늘 배운 표현을 복습했어요.", synonyms: ["다시 공부하다"], antonyms: ["예습하다"], partOfSpeech: "动词" },
      { term: "예습하다", pronunciation: "ye-seup-ha-da", meaning: "预习", example: "내일 수업 내용을 미리 예습하면 강의를 따라가기 쉬워요.", synonyms: ["미리 공부하다"], antonyms: ["복습하다"], partOfSpeech: "动词" },
      { term: "시험", pronunciation: "si-heom", meaning: "考试", example: "시험이 가까워져서 듣기와 읽기를 집중적으로 연습하고 있어요.", synonyms: ["평가"], antonyms: [], partOfSpeech: "名词" },
      { term: "성적", pronunciation: "seong-jeok", meaning: "成绩", example: "성적보다 중요한 것은 틀린 이유를 정확히 아는 거예요.", synonyms: ["점수"], antonyms: [], partOfSpeech: "名词" },
      { term: "합격하다", pronunciation: "hap-gyeok-ha-da", meaning: "合格、通过", example: "꾸준히 준비해서 TOPIK 시험에 합격하고 싶어요.", synonyms: ["통과하다"], antonyms: ["불합격하다"], partOfSpeech: "动词" },
      { term: "불합격하다", pronunciation: "bul-hap-gyeok-ha-da", meaning: "不合格", example: "한 번 불합격하더라도 부족한 부분을 고치면 됩니다.", synonyms: ["떨어지다"], antonyms: ["합격하다"], partOfSpeech: "动词" },
      { term: "도서관", pronunciation: "do-seo-gwan", meaning: "图书馆", example: "도서관 열람실에서 조용히 쓰기 연습을 했어요.", synonyms: ["자료실"], antonyms: [], partOfSpeech: "名词" },
      { term: "기숙사", pronunciation: "gi-suk-sa", meaning: "宿舍", example: "기숙사 방에서 룸메이트와 한국어로 짧게 대화했어요.", synonyms: ["생활관"], antonyms: [], partOfSpeech: "名词" },
      { term: "동아리", pronunciation: "dong-a-ri", meaning: "社团", example: "한국어 동아리에 가입한 뒤 말할 기회가 많아졌어요.", synonyms: ["모임", "클럽"], antonyms: [], partOfSpeech: "名词" },
      { term: "자료", pronunciation: "ja-ryo", meaning: "资料", example: "발표 자료를 만들 때 출처를 정확히 적었어요.", synonyms: ["정보", "문헌"], antonyms: [], partOfSpeech: "名词" },
      { term: "마감", pronunciation: "ma-gam", meaning: "截止、结束", example: "마감이 다가와서 오늘은 과제에 집중해야 해요.", synonyms: ["기한"], antonyms: ["시작"], partOfSpeech: "名词" }
    ]
  }
];
